# Generated by Django 6.0 on 2025-12-23 12:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('general', 'General'), ('important', 'Important'), ('urgent', 'Urgent')], default='general', max_length=20)),
                ('all_students', models.BooleanField(default=False)),
                ('all_teachers', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('send_email', models.BooleanField(default=True)),
                ('pin_to_dashboard', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('specific_recipients', models.ManyToManyField(blank=True, related_name='received_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
