# Generated by Django 5.2.4 on 2025-12-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_alter_announcement_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='all_csreps',
            field=models.BooleanField(default=False),
        ),
    ]
