# Generated by Django 5.2.4 on 2025-12-21 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('admin', '0001_initial'),  # Ensure admin migrations are applied first
    ]

    operations = [
        migrations.RunSQL(
            # Drop the foreign key constraint and alter column type
            sql="""
                DO $$ 
                DECLARE
                    r record;
                    user_id_attnum integer;
                BEGIN
                    -- Get the attribute number for user_id column
                    SELECT attnum INTO user_id_attnum
                    FROM pg_attribute
                    WHERE attrelid = 'django_admin_log'::regclass
                    AND attname = 'user_id';
                    
                    -- Find and drop all foreign key constraints on user_id column
                    FOR r IN 
                        SELECT conname
                        FROM pg_constraint c
                        JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = ANY(c.conkey)
                        WHERE c.conrelid = 'django_admin_log'::regclass
                        AND c.contype = 'f'
                        AND a.attnum = user_id_attnum
                    LOOP
                        EXECUTE format('ALTER TABLE django_admin_log DROP CONSTRAINT %I', r.conname);
                    END LOOP;
                    
                    -- Set all existing user_id values to NULL (we can't convert integer to UUID)
                    UPDATE django_admin_log SET user_id = NULL WHERE user_id IS NOT NULL;
                    
                    -- Alter the column type from integer to UUID
                    ALTER TABLE django_admin_log 
                    ALTER COLUMN user_id TYPE uuid USING NULL;
                    
                    -- Recreate the foreign key constraint pointing to users table
                    ALTER TABLE django_admin_log 
                    ADD CONSTRAINT django_admin_log_user_id_fkey 
                    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL;
                END $$;
            """,
            # Reverse migration: convert UUID back to integer (for rollback)
            reverse_sql="""
                DO $$ 
                DECLARE
                    r record;
                    user_id_attnum integer;
                BEGIN
                    -- Get the attribute number for user_id column
                    SELECT attnum INTO user_id_attnum
                    FROM pg_attribute
                    WHERE attrelid = 'django_admin_log'::regclass
                    AND attname = 'user_id';
                    
                    -- Find and drop all foreign key constraints on user_id column
                    FOR r IN 
                        SELECT conname
                        FROM pg_constraint c
                        JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = ANY(c.conkey)
                        WHERE c.conrelid = 'django_admin_log'::regclass
                        AND c.contype = 'f'
                        AND a.attnum = user_id_attnum
                    LOOP
                        EXECUTE format('ALTER TABLE django_admin_log DROP CONSTRAINT %I', r.conname);
                    END LOOP;
                    
                    -- Set all existing user_id values to NULL
                    UPDATE django_admin_log SET user_id = NULL WHERE user_id IS NOT NULL;
                    
                    -- Alter the column type from UUID to integer
                    ALTER TABLE django_admin_log 
                    ALTER COLUMN user_id TYPE integer USING NULL;
                END $$;
            """,
        ),
    ]
