# Generated by Django 5.2.4 on 2025-12-28 12:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_admin_updated_at_csrep_updated_at_student_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(default='normal', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_teacher_feedbacks', to='account.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_feedbacks', to='account.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Feedback',
                'verbose_name_plural': 'Teacher Feedbacks',
                'db_table': 'teacher_feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(default='normal', max_length=20)),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_teacher_reports', to='account.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to='account.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Report',
                'verbose_name_plural': 'Teacher Reports',
                'db_table': 'teacher_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
