# Generated by Django 5.2.4 on 2025-12-28 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_maskedlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('desktop_notifications', models.BooleanField(default=False)),
                ('sound_alerts', models.BooleanField(default=False)),
                ('student_messages', models.BooleanField(default=True)),
                ('announcements', models.BooleanField(default=True)),
                ('assignment_updates', models.BooleanField(default=True)),
                ('meeting_reminders', models.BooleanField(default=True)),
                ('grade_notifications', models.BooleanField(default=True)),
                ('teacher_messages', models.BooleanField(default=True)),
                ('new_announcements', models.BooleanField(default=True)),
                ('assignment_submissions', models.BooleanField(default=True)),
                ('meeting_reminders_teacher', models.BooleanField(default=True)),
                ('grade_submissions', models.BooleanField(default=True)),
                ('assignment_requests', models.BooleanField(default=True)),
                ('invoice_notifications', models.BooleanField(default=True)),
                ('content_review_alerts', models.BooleanField(default=True)),
                ('system_alerts', models.BooleanField(default=True)),
                ('csrep_notifications_enabled', models.BooleanField(default=True)),
                ('assignment_due_reminders', models.BooleanField(default=True)),
                ('meeting_reminders_enabled', models.BooleanField(default=True)),
                ('meeting_reminder_time', models.IntegerField(choices=[(15, '15 minutes before'), (30, '30 minutes before'), (60, '1 hour before'), (1440, '1 day before')], default=30)),
                ('grade_submission_reminders', models.BooleanField(default=True)),
                ('exam_reminders', models.BooleanField(default=True)),
                ('payment_reminders', models.BooleanField(default=True)),
                ('auto_refresh_dashboard', models.BooleanField(default=True)),
                ('refresh_interval', models.IntegerField(choices=[(5, 'Every 5 minutes'), (10, 'Every 10 minutes'), (15, 'Every 15 minutes'), (30, 'Every 30 minutes')], default=10)),
                ('default_date_range', models.CharField(choices=[('7', 'Last 7 days'), ('30', 'Last 30 days'), ('90', 'Last 90 days'), ('365', 'Last year')], default='30', max_length=10)),
                ('reminder_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('reminder_time', models.TimeField(default='09:00')),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('session_timeout', models.CharField(choices=[('15', '15 minutes'), ('30', '30 minutes'), ('60', '1 hour'), ('120', '2 hours'), ('never', 'Never')], default='60', max_length=20)),
                ('activity_log', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Notification Settings',
                'verbose_name_plural': 'User Notification Settings',
                'db_table': 'user_notification_settings',
            },
        ),
    ]
