# Generated by Django 5.2.4 on 2025-12-28 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_emailverificationtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
    ]
