# Generated by Django 5.2.4 on 2025-12-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_alter_meetingparticipant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingparticipant',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
