# Generated by Django 5.2.4 on 2025-12-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_alter_meetingparticipant_id'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "meetings" '
                        'ADD COLUMN IF NOT EXISTS "updated_at" timestamptz;'
                        'UPDATE "meetings" SET "updated_at" = NOW() '
                        'WHERE "updated_at" IS NULL;'
                        'ALTER TABLE "meetings" '
                        'ALTER COLUMN "updated_at" SET NOT NULL;'
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name='meeting',
                    name='updated_at',
                    field=models.DateTimeField(auto_now=True),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "meeting_participants" '
                        'ADD COLUMN IF NOT EXISTS "updated_at" timestamptz;'
                        'UPDATE "meeting_participants" SET "updated_at" = NOW() '
                        'WHERE "updated_at" IS NULL;'
                        'ALTER TABLE "meeting_participants" '
                        'ALTER COLUMN "updated_at" SET NOT NULL;'
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name='meetingparticipant',
                    name='updated_at',
                    field=models.DateTimeField(auto_now=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='meetingparticipant',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
