# Generated by Django 6.0 on 2025-12-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_add_updated_at_to_meeting_and_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingparticipant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
