# Generated by Django 6.0 on 2025-12-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0007_meeting_recording_created_at_meeting_recording_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='recording_created_at',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='recording_size',
        ),
        migrations.AlterField(
            model_name='meetingparticipant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
