# Generated by Django 5.2.4 on 2025-12-21 23:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_teacher_bio_teacher_experience_details_teacher_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('assignment', 'Assignment Solution'), ('solve-paper', 'Solve Online Paper'), ('do-exam', 'Do My Exam'), ('it-projects', 'IT Projects'), ('writing', 'Writing (All Types)')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in-process', 'In Process'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('on-hold', 'On Hold')], default='pending', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('exam_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('writing_type', models.CharField(blank=True, max_length=100, null=True)),
                ('num_pages', models.IntegerField(blank=True, null=True)),
                ('online_paper_type', models.CharField(blank=True, max_length=100, null=True)),
                ('other_paper_type', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_features', models.JSONField(blank=True, default=list)),
                ('completion_notes', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='account.student')),
            ],
            options={
                'db_table': 'assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('priority', models.CharField(default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='assingment.assignment')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('to_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_feedbacks', to='account.teacher')),
            ],
            options={
                'db_table': 'assignment_feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assignment_files/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('support', 'Supporting Document'), ('solution', 'Solution'), ('proof', 'Proof of Attempt'), ('result', 'Result Report')], default='support', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assingment.assignment')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assignment_files',
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helper', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='assingment.assignment')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='account.teacher')),
            ],
            options={
                'db_table': 'teacher_assignments',
                'unique_together': {('assignment', 'teacher')},
            },
        ),
    ]
