# Generated by Django 6.0 on 2025-12-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assingment', '0002_alter_assignmentfeedback_id_alter_assignmentfile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
    ]
