# Generated by Django 6.0 on 2025-12-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assingment', '0003_assignment_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in-process', 'In Process'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('on-hold', 'On Hold'), ('deleted', 'Deleted')], default='pending', max_length=20),
        ),
    ]
