# Generated by Django 5.2.4 on 2025-12-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assingment', '0012_alter_assignmentfeedback_id_alter_assignmentfile_id_and_more'),
    ]

    operations = [
        # NOTE:
        # Some environments already have these `updated_at` columns (schema drift / manual change),
        # which causes Postgres to fail with DuplicateColumn on a normal AddField.
        # We make the DB operation idempotent while still updating Django's migration state.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "assignment_feedbacks" '
                        'ADD COLUMN IF NOT EXISTS "updated_at" timestamptz;'
                        'UPDATE "assignment_feedbacks" SET "updated_at" = NOW() '
                        'WHERE "updated_at" IS NULL;'
                        'ALTER TABLE "assignment_feedbacks" '
                        'ALTER COLUMN "updated_at" SET NOT NULL;'
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name='assignmentfeedback',
                    name='updated_at',
                    field=models.DateTimeField(auto_now=True),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "assignment_files" '
                        'ADD COLUMN IF NOT EXISTS "updated_at" timestamptz;'
                        'UPDATE "assignment_files" SET "updated_at" = NOW() '
                        'WHERE "updated_at" IS NULL;'
                        'ALTER TABLE "assignment_files" '
                        'ALTER COLUMN "updated_at" SET NOT NULL;'
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name='assignmentfile',
                    name='updated_at',
                    field=models.DateTimeField(auto_now=True),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "teacher_assignments" '
                        'ADD COLUMN IF NOT EXISTS "updated_at" timestamptz;'
                        'UPDATE "teacher_assignments" SET "updated_at" = NOW() '
                        'WHERE "updated_at" IS NULL;'
                        'ALTER TABLE "teacher_assignments" '
                        'ALTER COLUMN "updated_at" SET NOT NULL;'
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name='teacherassignment',
                    name='updated_at',
                    field=models.DateTimeField(auto_now=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='assignmentfeedback',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='assignmentfile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
