# Generated by Django 5.2.4 on 2025-12-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
