# Generated by Django 5.2.4 on 2025-12-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_homeworksubmission_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
