# Generated by Django 6.0 on 2025-12-29 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadparticipant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
