# Generated by Django 5.2.4 on 2025-12-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0002_threadparticipant_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
