# Generated by Django 5.2.4 on 2025-12-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='task',
            new_name='title',
        ),
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='todo',
            name='variety',
            field=models.CharField(choices=[('academic', 'Academic'), ('administrative', 'Administrative'), ('meeting', 'Meeting'), ('grading', 'Grading'), ('preparation', 'Preparation'), ('personal', 'Personal'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
