# Generated by Django 5.2.4 on 2025-12-24 00:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreSignInSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('visitor_name', models.CharField(max_length=255)),
                ('visitor_concern', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_message_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='PreSignInMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='pre_signin_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_system', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='preSigninMessages.presigninsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
