# Generated by Django 5.2.4 on 2025-12-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preSigninMessages', '0002_presigninsession_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='presigninsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
