# Generated by Django 5.2.4 on 2025-12-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preSigninMessages', '0003_presigninsession_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='presigninmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
